version: '3.8'

services:
  arm-credit-service:
    build:
      context: .
    container_name: arm-credit-service
    ports:
      - "9091:9091"
    restart: always
    environment:
      CONNECTION_URL: jdbc:postgresql://postgres:5432/credit-db
      CONNECTION_USERNAME: postgres
      CONNECTION_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: 'postgres:13.8-alpine'
    container_name: postgres

    environment:
      POSTGRES_DB: credit-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      start_period: 15s
      timeout: 3s
      interval: 10s
      retries: 12
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - arm-credit-service

volumes:
  postgres:

networks:
  app-network: